# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/29047/Desktop/final17/final17.srcs/sources_1/ip/insROM_1/insROM.xci
# IP: The module: 'insROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29047/Desktop/final17/final17.srcs/sources_1/ip/insROM_1/insROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/29047/Desktop/final17/final17.srcs/sources_1/ip/insROM_1/insROM.xci
# IP: The module: 'insROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29047/Desktop/final17/final17.srcs/sources_1/ip/insROM_1/insROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'insROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
